model:
  version: "v1"

  flan_t5:
    base_model: "google/flan-t5-small"
    model_type: "seq2seq"
    output_dir: "checkpoints/flan-t5-small"
    target_modules: ["q", "v"]
  
  llama:
    base_model: "unsloth/Llama-3.2-1B-Instruct"
    model_type: "causal"
    output_dir: "checkpoints/llama-1b"
    target_modules: ["q_proj","v_proj"]

  lora:
    r: 4
    alpha: 16
    dropout: 0.05